INSERT INTO regulator values
("Da Afghanistan Bank", "APAC", "Afghanitan", "https://dab.gov.af/")
("Albanian Financial Supervisory Authority", "EMEA", "Albania", "https://amf.gov.al/")
("Commission of the Organization and Supervision of the Algiers Stock Exchange", "EMEA", "Algeria", "http://www.cosob.org/")
("Andorran Financial Authority", "EMEA", "Andorra", "https://www.afa.ad/")
("Anguilla Financial Services Commission", "Americas", "Anguilla", "https://www.fsc.org.ai/")
("Financial Services Regulatory Commission", "Americas", "Antigua & Barbuda", "https://www.fsrc.gov.ag/")
("National Securities Commission", "Americas", "Argentina", "https://www.argentina.gob.ar/cnv/")
("Central Bank of Armenia", "APAC", "Armenia", "https://www.cba.am/")
("Australian Prudential Regulation Authority", "APAC", "Australia", "https://www.apra.gov.au/")
("Australian Securities and Investments Commission", "APAC", "Australia", "https://asic.gov.au/")
("Australian Takeovers Panel", "APAC", "Australia", "https://www.takeovers.gov.au/")
("Financial Market Authority", "EMEA", "Austria", "https://www.fma.gv.at/")
("Oesterreichische Nationalbank", "EMEA", "Austria", "https://www.oenb.at/")
("Austrian Takeover Commission", "EMEA", "Austria", "https://www.takeover.at/")
("Central Bank of the Republic of Azerbaijan", "APAC", "Azerbaijan", "https://www.cbar.az/")
("Securities Commission of the Bahamas", "Americas", "Bahamas", "http://www.scb.gov.bs/")
("Central Bank of Bahrain", "APAC", "Bahrain", "http://www.cbb.gov.bh/")
("Securities and Exchange Commission", "APAC", "Bangladesh", "https://www.sec.gov.bd/")
("Central Bank of Barbados", "Americas", "Barbados", "http://www.centralbank.org.bb/")
("Financial Services and Markets Authority", "EMEA", "Belgium", "https://www.fsma.be/")
("National Bank of Belgium", "EMEA", "Belgium", "https://www.nbb.be/")
("International Financial Services Commission", "Americas", "Belize", "https://www.ifsc.gov.bz/")
-- ("Central Bank of the States of West Africa", "EMEA", "Benin", "Burkina Faso", "Côte d'Ivoire", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo", "https://www.bceao.int/")
("Bermuda Monetary Authority", "Americas", "Bermuda", "https://www.bma.bm/")
("Supervisory Authority of the Financial System", "Americas", "Bolivia", "https://www.asfi.gob.bo/")
("Securities Commission of the Federation of Bosnia and Herzegovina", "EMEA", "Bosnia Herzegovina", "http://www.komvp.gov.ba/")
("Securities Commission for Republika Srpska", "EMEA", "Bosnia Herzegovina", "http://www.secrs.gov.ba/")
("Central Bank of Brazil", "Americas", "Brazil", "https://www.bcb.gov.br/")
("Securities and Exchange Commission of Brazil", "Americas", "Brazil", "https://www.gov.br/cvm/pt-br/")
("Supervisory Agent for Private Insurance", "Americas", "Brazil", "http://novosite.susep.gov.br/")
("British Virgin Islands Financial Services Commission", "Americas", "British Virgin Islands", "https://www.bvifsc.vg/")
("Ministry of Finance and Economy", "APAC", "Brunei", "https://www.mofe.gov.bn/")
("Financial Supervision Commission", "EMEA", "Bulgaria", "https://www.fsc.bg/")
("Financial Markets Authority", "Americas", "Canada", "https://lautorite.qc.ca/")
("British Columbia Securities Commission", "Americas", "Canada", "https://www.bcsc.bc.ca/")
("Canadian Securities Administrators", "Americas", "Canada", "https://www.securities-administrators.ca/")
("Financial Services Commission of Ontario", "Americas", "Canada", "http://www.fsco.gov.on.ca/")
("Investment Industry Regulatory Organization of Canada", "Americas", "Canada", "https://www.iiroc.ca/")
("Mutual Fund Dealers Association", "Americas", "Canada", "http://www.mfda.ca/")
("Ontario Securities Commission", "Americas", "Canada", "https://www.osc.gov.on.ca/")
("Office of the Superintendent of Financial Institutions", "Americas", "Canada", "https://www.osfi-bsif.gc.ca/")
("Cayman Islands Monetary Authority", "Americas", "Cayman Islands", "https://www.cima.ky/")
("Commission for the Financial Market", "Americas", "Chile", "http://www.cmfchile.cl/")
("China Banking and Insurance Regulatory Commission", "APAC", "China", "https://www.cbirc.gov.cn/")
("China Securities Regulatory Commission", "APAC", "China", "http://www.csrc.gov.cn/")
("Financial Supervision of Colombia", "Americas", "Colombia", "https://www.superfinanciera.gov.co/")
("General Supervision of Insurance", "Americas", "Costa Rica", "https://www.sugese.fi.cr/")
("General Supervision of Securities", "Americas", "Costa Rica", "https://www.sugeval.fi.cr/")
("Croatian Financial Services Supervisory Agency", "EMEA", "Croatia", "https://www.hanfa.hr/")
("Central Bank of Cyprus", "EMEA", "Cyprus", "https://www.centralbank.cy/")
("Cyprus Securities and Exchange Commission", "EMEA", "Cyprus", "https://www.cysec.gov.cy/")
("Cyprus Insurance Companies Control Service", "EMEA", "Cyprus", "http://mof.gov.cy/gr/")
("Czech National Bank", "EMEA", "Czech Republic", "https://www.cnb.cz/")
("Danish Financial Services Authority", "EMEA", "Denmark", "https://www.dfsa.dk/")
("Supervision of the Banks of the Dominican Republic", "Americas", "Dominican Republic", "https://sb.gob.do/")
("Central Bank of the Dominican Republic", "Americas", "Dominican Republic", "https://www.bancentral.gov.do/")
("Supervision of Companies", "Americas", "Ecuador", "https://www.supercias.gob.ec/")
("Finance Regulatory Authority", "EMEA", "Egypt", "http://www.fra.gov.eg/")
("Superintendence of the Financial System", "Americas", "El Salvador", "https://ssf.gob.sv/")
("Financial Supervision Authority", "EMEA", "Estonia", "http://www.fi.ee/")
("Estonian Bank", "EMEA", "Estonia", "http://www.eestipank.ee/")
("Insurance Authority of the Faroe Islands", "EMEA", "Faroe Islands", "https://www.tryggingareftirlitid.fo/")
("Financial Supervisory Authority", "EMEA", "Finland", "https://www.finanssivalvonta.fi/")
("French Prudential Supervisory Authority", "EMEA", "France", "https://www.banque-france.fr/")
("Financial Markets Authority", "EMEA", "France", "https://www.amf-france.org/")
("Single Register of Insurance Intermediaries", "Banking & Finance", "EMEA", "France", "https://www.orias.fr/")
("National Bank of Georgia", "APAC", "Georgia", "https://www.nbg.gov.ge/")
("Federal Financial Supervisory Authority", "EMEA", "Germany", "http://www.bafin.de/")
("Bank of Ghana", "EMEA", "Ghana", "http://www.bog.gov.gh/")
("Securities and Exchange Commission", "EMEA", "Ghana", "http://www.sec.gov.gh/")
("Hellenic Capital Market Commission", "EMEA", "Greece", "http://www.hcmc.gr/")
("Grenada Authority for the Regulation of Financial Institutions", "Americas", "Grenada", "http://www.garfin.gd/")
("Supervision of Banks", "Americas", "Guatemala", "http://www.sib.gob.gt/")
("Guernsey Financial Services Commission", "EMEA", "Guernsey", "http://www.gfsc.gg/")
("National Banks and Securities Commission", "Americas", "Honduras", "https://gpuf.cnbs.gob.hn/")
("Hong Kong Monetary Authority", "APAC", "Hong Kong", "http://www.hkma.gov.hk/")
("Securities and Futures Commission", "APAC", "Hong Kong", "http://www.sfc.hk/")
("The Central Bank of Hungary", "EMEA", "Hungary", "http://felugyelet.mnb.hu/")
("Central Bank of Iceland", "EMEA", "Iceland", "https://www.cb.is/")
("Insurance Regulatory and Development Authority", "APAC", "India", "https://www.irda.gov.in/")
("Ministry of Corporate Affairs", "APAC", "India", "http://www.mca.gov.in/")
("Pension Fund Regulatory and Development Authority", "APAC", "India", "http://pfrda.org.in/")
("Reserve Bank of India", "APAC", "India", "http://www.rbi.org.in/")
("Securities and Exchange Board of India", "APAC", "India", "https://www.sebi.gov.in/")
("Financial Services Authority", "APAC", "Indonesia", "http://www.ojk.go.id/")
("Bank of Indonesia", "APAC", "Indonesia", "http://www.bi.go.id/")
("Iraq Securities Commission", "APAC", "Iraq", "https://www.isc.gov.iq/")
("Central Bank and Financial Services Authority of Ireland", "EMEA", "Ireland", "https://www.centralbank.ie/")
("Irish Takeover Panel", "EMEA", "Ireland", "http://irishtakeoverpanel.ie/")
("Isle of Man Financial Services Authority", "EMEA", "Isle of Man", "https://www.iomfsa.im/")
("Israel Securities Authority", "APAC", "Israel", "http://www.isa.gov.il/")
("National Commission for Companies and the Stock Exchange", "EMEA", "Italy", "http://www.consob.it/")
("Institute for the Supervision of Insurance", "EMEA", "Italy", "https://www.ivass.it/")
("Financial Services Commission", "Americas", "Jamaica", "http://www.fscjamaica.org/")
("Securities and Exchange Commission", "APAC", "Japan", "http://www.fsa.go.jp/")
("Securities and Exchange Surveillance Commission", "APAC", "Japan", "http://www.fsa.go.jp/sesc/")
("Jersey Financial Services Commission", "EMEA", "Jersey", "http://www.jerseyfsc.org/")
("Jordan Securities Commission", "APAC", "Jordan", "https://jsc.gov.jo/")
("Agency for Regulation and Development of the Financial Market of the Republic of Kazakhstan", "APAC", "Kazakhstan", "https://www.gov.kz/memleket/entities/ardfm")
("Financial and Capital Market Commission", "EMEA", "Latvia", "http://www.fktk.lv/")
("Banking Control Commission of Lebanon", "APAC", "Lebanon", "http://www.bccl.gov.lb/")
("Financial Market Authority", "EMEA", "Liechtenstein", "https://www.fma-li.li/")
("Bank of Lithuania", "EMEA", "Lithuania", "https://www.lb.lt/")
("Insurance Commission", "EMEA", "Luxembourg", "http://www.caa.lu/")
("Commission de Surveillance du Secteur Financier", "EMEA", "Luxembourg", "https://www.cssf.lu/")
("Securities Commission Malaysia", "APAC", "Malaysia", "http://www.sc.com.my/")
("Malta Financial Services Authority", "EMEA", "Malta", "http://www.mfsa.com.mt/")
("Central Bank of Mauritania", "EMEA", "Mauritania", "https://www.bcm.mr/")
("Bank of Mauritius", "EMEA", "Mauritius", "https://www.bom.mu/")
("Financial Services Commission", "EMEA", "Mauritius", "https://www.fscmauritius.org/")
("National Commission for Banks and Securities", "Americas", "Mexico", "http://www.cnbv.gob.mx/")
("National Commission for Financial Markets", "EMEA", "Moldova", "https://www.cnpf.md/")
("Insurance Supervision Agency", "EMEA", "Montenegro", "http://ano.me/")
("Montserrat Financial Services Commission", "Americas", "Montserrat", "http://www.fscmontserrat.org/")
("Moroccan Capital Market Authority", "EMEA", "Morocco", "http://www.ammc.ma/")
("Dutch Authority for the Financial Markets", "EMEA", "Netherlands", "http://www.afm.nl/")
("Financial Markets Authority", "APAC", "New Zealand", "https://www.fma.govt.nz/")
("National Bank of the Republic of North Macedonia", "EMEA", "North Macedonia", "http://www.nbrm.mk/")
("Financial Supervisory Authority of Norway", "EMEA", "Norway", "http://www.finanstilsynet.no/")
("Capital Market Authority", "APAC", "Oman", "http://www.cma.gov.om/")
("Securities and Exchange Commission of Pakistan", "APAC", "Pakistan", "http://www.secp.gov.pk/")
("Superintendence of the Panama Stock Market", "Americas", "Panama", "https://www.supervalores.gob.pa/")
("Superintendence of the Securities Market", "Americas", "Peru", "http://www.smv.gob.pe/")
("Securities and Exchange Commission Philippines", "APAC", "Philippines", "http://www.sec.gov.ph/")
("Polish Financial Supervision Authority", "EMEA", "Poland", "https://www.knf.gov.pl/")
("Insurance and Pension Funds Supervisory Authority", "EMEA", "Portugal", "https://www.asf.com.pt/")
("Portuguese Securities Market Commission", "EMEA", "Portugal", "https://www.cmvm.pt/")
("Qatar Financial Centre Regulatory Authority", "APAC", "Qatar", "http://www.qfcra.com/")
("Qatar Financial Markets Authority", "APAC", "Qatar", "https://www.qfma.org.qa/")
("Financial Services Commission", "APAC", "Republic of Korea", "http://www.fsc.go.kr/")
("Financial Supervisory Service", "APAC", "Republic of Korea", "http://www.fss.or.kr/")
("Romanian Financial Supervisory Authority", "EMEA", "Romania", "https://asfromania.ro/")
("Central Bank of the Russian Federation (Bank of Russia)", "EMEA", "Russian Federation", "https://www.cbr.ru/")
("Financial Services Regulatory Commission (St. Kitts branch)", "Americas", "Saint Kitts and Nevis", "http://fsrc.kn/")
("Nevis Financial Services Regulation and Supervision Department", "Americas", "Saint Kitts and Nevis", "http://www.nevisfsrc.com/")
("Financial Services Regulatory Authority Saint Lucia", "Americas", "Saint Lucia", "https://fsrastlucia.org/")
("Financial Services Authority", "Americas", "Saint Vincent and the Grenadines", "http://svgfsa.com/")
("Central Bank of the Republic of San Marino", "EMEA", "San Marino", "https://www.bcsm.sm/")
("Capital Market Authority", "APAC", "Saudi Arabia", "https://cma.org.sa/")
("Republic of Serbia Securities Commission", "EMEA", "Serbia", "http://www.sec.gov.rs/")
("Central Bank of Seychelles", "EMEA", "Seychelles", "http://www.cbs.sc/")
("Monetary Authority of Singapore", "APAC", "Singapore", "http://www.mas.gov.sg/")
("National Bank of Slovakia", "EMEA", "Slovakia", "http://www.nbs.sk/")
("Securities Market Agency", "EMEA", "Slovenia", "http://www.a-tvp.si/")
("The Financial Sector Conduct Authority", "EMEA", "South Africa", "https://www.fsca.co.za/")
("National Credit Regulator", "EMEA", "South Africa", "http://www.ncr.org.za/")
("South African Reserve Bank", "EMEA", "South Africa", "https://www.resbank.co.za/")
("Swedish Financial Supervisory Authority", "EMEA", "Sweden", "https://www.fi.se/")
("Swiss Financial Market Supervisory Authority", "EMEA", "Switzerland", "http://www.finma.ch/")
("Capital Markets and Securities Authority", "EMEA", "Tanzania", "http://www.cmsa-tz.org/")
("Bank of Thailand", "APAC", "Thailand", "https://www.bot.or.th/")
("Capital Markets Board of Turkey", "APAC", "Turkey", "http://www.cmb.gov.tr/")
("Capital Markets Authority", "EMEA", "Uganda", "http://www.cmauganda.co.ug/")
("Dubai Financial Services Authority", "APAC", "United Arab Emirates", "https://www.dfsa.ae/")
("Securities and Commodities Authority", "APAC", "United Arab Emirates", "https://www.sca.gov.ae/")
("Financial Conduct Authority", "EMEA", "United Kingdom", "http://www.fca.org.uk/")
("Panel on Takeovers and Mergers", "EMEA", "United Kingdom", "http://www.thetakeoverpanel.org.uk/")
("Prudential Regulation Authority", "EMEA", "United Kingdom", "http://www.bankofengland.co.uk/")
("Office of the Comptroller of the Currency", "Americas", "United States", "http://www.occ.gov/")
("Securities and Exchange Commission", "Americas", "United States", "http://www.sec.gov/")
("US Department of the Treasury", "Americas", "United States", "http://www.treasury.gov/")
("Central Bank of Uruguay", "Americas", "Uruguay", "http://www.bcu.gub.uy/")
("Commodity Futures Trading Commission", "Americas", "USA", "http://www.cftc.gov/")
("Financial Information Authority", "EMEA", "Vatican City", "http://www.aif.va/")
("National Superintendency of Securities of Venezuela", "Americas", "Venezuela", "https://www.sunaval.gob.ve/quienes-somos/")
("State Securities Commission", "APAC", "Vietnam", "http://www.ssc.gov.vn/")
("Financial Supervisory Authority", "EMEA", "Iceland", "https://en.fme.is/")
("Consumer Financial Protection Bureau", "Americas", "United States", "https://www.consumerfinance.gov/")
("European Securities and Markets Association", "EMEA", "ESMA", "https://www.esma.europa.eu/")
("Financial Action Task ForceSupranational", "null", "https://www.fatf-gafi.org/")
("Financial and Consumer Services Commission", "Americas", "Canada", "https://fcnb.ca/en/")
("Federal Deposit Insurance Corporation", "Americas", "United States", "https://www.fdic.gov/")
("Financial Crimes Enforcement Network", "Americas", "United States", "https://www.fincen.gov/")
("Financial Industry Regulatory Authority", "Americas", "United States", "https://www.finra.org/")
("International Organization of Securities CommissionsSupranational", "null", "https://www.iosco.org/")
("National Futures Association", "Americas", "United States", "https://www.nfa.futures.org/")
("Manitoba Securities Commission", "Americas", "Canada", "https://mbsecurities.ca/")
("Office of Foreign Assets Control", "Americas", "United States", "https://home.treasury.gov/")
("Securities and Exchange Commission", "EMEA", "Nigeria", "https://sec.gov.ng/")
("Securities and Exchange Commission", "APAC", "Thailand", "https://www.sec.or.th/")
("Federal Reserve System", "Americas", "United States", "https://www.federalreserve.gov/")
("Comisión Nacional del Mercado de Valores", "EMEA", "Spain", "https://www.cnmv.es/")
("European Insurance and Occupational Pensions Authority", "EMEA", "Supranational", "https://www.eiopa.europa.eu/")
("European Banking Authority", "EMEA", "Supranational", "https://www.eba.europa.eu/")
