-- taken from page 2 of  https://images.transparencycdn.org/images/CPI-2023-Report.pdf";
-- rearaged stlightly for all score and name to fit each on one line";
-- change "Bahams" to "The Bahamas"
-- change "Cabo Verde" to "Cape Verde"
-- change "Cote d'Ivoire" to "Cote D'Ivoire (Ivory Coast)"
-- change "Czechia" to "Czech Republic"
-- change "Timor-Leste" to "East Timor"
-- change "Fiji" to "Fiji Islands"
-- change "Gambia" to "Gambia The"
-- change "Hong Kong" to "Hong Kong S.A.R."
-- change "Korea, South" to "South Korea"
-- change "Korea, North" to "North Korea"
-- change "Fiji" to "Fiji Islands"

UPDATE country SET transparency = 69 WHERE name = "Barbados";
UPDATE country SET transparency = 69 WHERE name = "United States";
UPDATE country SET transparency = 68 WHERE name = "Bhutan";
UPDATE country SET transparency = 68 WHERE name = "United Arab Emirates";
UPDATE country SET transparency = 67 WHERE name = "Taiwan";
UPDATE country SET transparency = 66 WHERE name = "Chile";
UPDATE country SET transparency = 64 WHERE name = "The Bahamas";
UPDATE country SET transparency = 64 WHERE name = "Cape Verde";
UPDATE country SET transparency = 63 WHERE name = "South Korea";
UPDATE country SET transparency = 62 WHERE name = "Israel";
UPDATE country SET transparency = 61 WHERE name = "Lithuania";
UPDATE country SET transparency = 61 WHERE name = "Portugal";
UPDATE country SET transparency = 60 WHERE name = "Latvia";
UPDATE country SET transparency = 60 WHERE name = "Saint Vincent and the Grenadines";
UPDATE country SET transparency = 60 WHERE name = "Spain";
UPDATE country SET transparency = 59 WHERE name = "Botswana";
UPDATE country SET transparency = 58 WHERE name = "Qatar";
UPDATE country SET transparency = 57 WHERE name = "Czech Republic";
UPDATE country SET transparency = 56 WHERE name = "Dominica";
UPDATE country SET transparency = 56 WHERE name = "Italy";
UPDATE country SET transparency = 56 WHERE name = "Slovenia";
UPDATE country SET transparency = 55 WHERE name = "Costa Rica";
UPDATE country SET transparency = 55 WHERE name = "Saint Lucia";
UPDATE country SET transparency = 43 WHERE name = "Benin";
UPDATE country SET transparency = 43 WHERE name = "Ghana";
UPDATE country SET transparency = 43 WHERE name = "Oman";
UPDATE country SET transparency = 43 WHERE name = "Senegal";
UPDATE country SET transparency = 43 WHERE name = "Solomon Islands";
UPDATE country SET transparency = 43 WHERE name = "East Timor";
UPDATE country SET transparency = 42 WHERE name = "Bahrain";
UPDATE country SET transparency = 42 WHERE name = "China";
UPDATE country SET transparency = 42 WHERE name = "Cuba";
UPDATE country SET transparency = 42 WHERE name = "Hungary";
UPDATE country SET transparency = 42 WHERE name = "Moldova";
UPDATE country SET transparency = 42 WHERE name = "North Macedonia";
UPDATE country SET transparency = 42 WHERE name = "Trinidad and Tobago";
UPDATE country SET transparency = 41 WHERE name = "Burkina Faso";
UPDATE country SET transparency = 41 WHERE name = "Kosovo";
UPDATE country SET transparency = 41 WHERE name = "South Africa";
UPDATE country SET transparency = 41 WHERE name = "Vietnam";
UPDATE country SET transparency = 40 WHERE name = "Colombia";
UPDATE country SET transparency = 40 WHERE name = "Cote D'Ivoire (Ivory Coast)";
UPDATE country SET transparency = 40 WHERE name = "Guyana";
UPDATE country SET transparency = 40 WHERE name = "Suriname";
UPDATE country SET transparency = 40 WHERE name = "Tanzania";
UPDATE country SET transparency = 40 WHERE name = "Tunisia";
UPDATE country SET transparency = 90 WHERE name = "Denmark";
UPDATE country SET transparency = 87 WHERE name = "Finland";
UPDATE country SET transparency = 85 WHERE name = "New Zealand";
UPDATE country SET transparency = 84 WHERE name = "Norway";
UPDATE country SET transparency = 83 WHERE name = "Singapore";
UPDATE country SET transparency = 82 WHERE name = "Sweden";
UPDATE country SET transparency = 82 WHERE name = "Switzerland";
UPDATE country SET transparency = 79 WHERE name = "Netherlands";
UPDATE country SET transparency = 78 WHERE name = "Germany";
UPDATE country SET transparency = 78 WHERE name = "Luxembourg";
UPDATE country SET transparency = 77 WHERE name = "Ireland";
UPDATE country SET transparency = 76 WHERE name = "Canada";
UPDATE country SET transparency = 76 WHERE name = "Estonia";
UPDATE country SET transparency = 75 WHERE name = "Australia";
UPDATE country SET transparency = 75 WHERE name = "Hong Kong S.A.R.";
UPDATE country SET transparency = 73 WHERE name = "Belgium";
UPDATE country SET transparency = 73 WHERE name = "Japan";
UPDATE country SET transparency = 73 WHERE name = "Uruguay";
UPDATE country SET transparency = 72 WHERE name = "Iceland";
UPDATE country SET transparency = 71 WHERE name = "Austria";
UPDATE country SET transparency = 71 WHERE name = "France";
UPDATE country SET transparency = 71 WHERE name = "Seychelles";
UPDATE country SET transparency = 71 WHERE name = "United Kingdom";
UPDATE country SET transparency = 54 WHERE name = "Poland";
UPDATE country SET transparency = 54 WHERE name = "Slovakia";
UPDATE country SET transparency = 53 WHERE name = "Cyprus";
UPDATE country SET transparency = 53 WHERE name = "Georgia";
UPDATE country SET transparency = 53 WHERE name = "Grenada";
UPDATE country SET transparency = 53 WHERE name = "Rwanda";
UPDATE country SET transparency = 52 WHERE name = "Fiji";
UPDATE country SET transparency = 52 WHERE name = "Saudi Arabia";
UPDATE country SET transparency = 51 WHERE name = "Malta";
UPDATE country SET transparency = 51 WHERE name = "Mauritius";
UPDATE country SET transparency = 50 WHERE name = "Croatia";
UPDATE country SET transparency = 50 WHERE name = "Malaysia";
UPDATE country SET transparency = 49 WHERE name = "Greece";
UPDATE country SET transparency = 49 WHERE name = "Namibia";
UPDATE country SET transparency = 48 WHERE name = "Vanuatu";
UPDATE country SET transparency = 47 WHERE name = "Armenia";
UPDATE country SET transparency = 46 WHERE name = "Jordan";
UPDATE country SET transparency = 46 WHERE name = "Kuwait";
UPDATE country SET transparency = 46 WHERE name = "Montenegro";
UPDATE country SET transparency = 46 WHERE name = "Romania";
UPDATE country SET transparency = 45 WHERE name = "Bulgaria";
UPDATE country SET transparency = 45 WHERE name = "São Tomé and Príncipe";
UPDATE country SET transparency = 44 WHERE name = "Jamaica";
UPDATE country SET transparency = 39 WHERE name = "India";
UPDATE country SET transparency = 39 WHERE name = "Kazakhstan";
UPDATE country SET transparency = 39 WHERE name = "Lesotho";
UPDATE country SET transparency = 39 WHERE name = "Maldives";
UPDATE country SET transparency = 38 WHERE name = "Morocco";
UPDATE country SET transparency = 37 WHERE name = "Argentina";
UPDATE country SET transparency = 37 WHERE name = "Albania";
UPDATE country SET transparency = 37 WHERE name = "Belarus";
UPDATE country SET transparency = 37 WHERE name = "Ethiopia";
UPDATE country SET transparency = 37 WHERE name = "Gambia The";
UPDATE country SET transparency = 37 WHERE name = "Zambia";
UPDATE country SET transparency = 36 WHERE name = "Algeria";
UPDATE country SET transparency = 36 WHERE name = "Brazil";
UPDATE country SET transparency = 36 WHERE name = "Serbia";
UPDATE country SET transparency = 36 WHERE name = "Ukraine";
UPDATE country SET transparency = 35 WHERE name = "Bosnia and Herzegovina";
UPDATE country SET transparency = 35 WHERE name = "Dominican Republic";
UPDATE country SET transparency = 35 WHERE name = "Egypt";
UPDATE country SET transparency = 35 WHERE name = "Nepal";
UPDATE country SET transparency = 35 WHERE name = "Panama";
UPDATE country SET transparency = 35 WHERE name = "Sierra Leone";
UPDATE country SET transparency = 35 WHERE name = "Thailand";
UPDATE country SET transparency = 34 WHERE name = "Ecuador";
UPDATE country SET transparency = 34 WHERE name = "Indonesia";
UPDATE country SET transparency = 34 WHERE name = "Malawi";
UPDATE country SET transparency = 34 WHERE name = "Philippines";
UPDATE country SET transparency = 34 WHERE name = "Sri Lanka";
UPDATE country SET transparency = 34 WHERE name = "Turkey";
UPDATE country SET transparency = 33 WHERE name = "Angola";
UPDATE country SET transparency = 33 WHERE name = "Mongolia";
UPDATE country SET transparency = 33 WHERE name = "Peru";
UPDATE country SET transparency = 33 WHERE name = "Uzbekistan";
UPDATE country SET transparency = 32 WHERE name = "Niger";
UPDATE country SET transparency = 31 WHERE name = "El Salvador";
UPDATE country SET transparency = 31 WHERE name = "Kenya";
UPDATE country SET transparency = 31 WHERE name = "Mexico";
UPDATE country SET transparency = 31 WHERE name = "Togo";
UPDATE country SET transparency = 30 WHERE name = "Djibouti";
UPDATE country SET transparency = 30 WHERE name = "Eswatini";
UPDATE country SET transparency = 30 WHERE name = "Mauritania";
UPDATE country SET transparency = 29 WHERE name = "Bolivia";
UPDATE country SET transparency = 29 WHERE name = "Pakistan";
UPDATE country SET transparency = 29 WHERE name = "Papua New Guinea";
UPDATE country SET transparency = 28 WHERE name = "Gabon";
UPDATE country SET transparency = 28 WHERE name = "Laos";
UPDATE country SET transparency = 28 WHERE name = "Mali";
UPDATE country SET transparency = 28 WHERE name = "Paraguay";
UPDATE country SET transparency = 27 WHERE name = "Cameroon";
UPDATE country SET transparency = 26 WHERE name = "Guinea";
UPDATE country SET transparency = 26 WHERE name = "Kyrgyzstan";
UPDATE country SET transparency = 26 WHERE name = "Russia";
UPDATE country SET transparency = 26 WHERE name = "Uganda";
UPDATE country SET transparency = 25 WHERE name = "Liberia";
UPDATE country SET transparency = 25 WHERE name = "Madagascar";
UPDATE country SET transparency = 25 WHERE name = "Mozambique";
UPDATE country SET transparency = 25 WHERE name = "Nigeria";
UPDATE country SET transparency = 24 WHERE name = "Bangladesh";
UPDATE country SET transparency = 24 WHERE name = "Central African Republic";
UPDATE country SET transparency = 24 WHERE name = "Iran";
UPDATE country SET transparency = 24 WHERE name = "Lebanon";
UPDATE country SET transparency = 24 WHERE name = "Zimbabwe";
UPDATE country SET transparency = 23 WHERE name = "Azerbaijan";
UPDATE country SET transparency = 23 WHERE name = "Guatemala";
UPDATE country SET transparency = 23 WHERE name = "Honduras";
UPDATE country SET transparency = 23 WHERE name = "Iraq";
UPDATE country SET transparency = 22 WHERE name = "Cambodia";
UPDATE country SET transparency = 22 WHERE name = "Congo";
UPDATE country SET transparency = 22 WHERE name = "Guinea-Bissau";
UPDATE country SET transparency = 21 WHERE name = "Eritrea";
UPDATE country SET transparency = 20 WHERE name = "Afghanistan";
UPDATE country SET transparency = 20 WHERE name = "Burundi";
UPDATE country SET transparency = 20 WHERE name = "Chad";
UPDATE country SET transparency = 20 WHERE name = "Comoros";
UPDATE country SET transparency = 20 WHERE name = "Democratic Republic of the Congo";
UPDATE country SET transparency = 20 WHERE name = "Myanmar";
UPDATE country SET transparency = 20 WHERE name = "Sudan";
UPDATE country SET transparency = 20 WHERE name = "Tajikistan";
UPDATE country SET transparency = 18 WHERE name = "Libya";
UPDATE country SET transparency = 18 WHERE name = "Turkmenistan";
UPDATE country SET transparency = 17 WHERE name = "Equatorial Guinea";
UPDATE country SET transparency = 17 WHERE name = "Haiti";
UPDATE country SET transparency = 17 WHERE name = "North Korea";
UPDATE country SET transparency = 17 WHERE name = "Nicaragua";
UPDATE country SET transparency = 16 WHERE name = "Yemen";
UPDATE country SET transparency = 13 WHERE name = "South Sudan";
UPDATE country SET transparency = 13 WHERE name = "Syria";
UPDATE country SET transparency = 13 WHERE name = "Venezuela";
UPDATE country SET transparency = 11 WHERE name = "Somalia";
